name: Get Weibo Follow
on:
  schedule:
    - cron: '*/30 */1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install NodeJS
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: 16

      - name: install dependencies
        run: | 
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm i

      - name: run puppeteer
        uses: ugaxm/puppeteer-headful@v2
        env:
          CI: 'true'
          COOKIE_TOKEN: ${{ secrets.COOKIE_TOKEN }}
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
          TARGET_WEIBO: ${{ secrets.TARGET_WEIBO }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with: 
          args: npm start
